export const PATHS = {
    ROOT: "/",
    HOME: "/home",
    ABOUT: "/about",
    CART: "/cart",
    WISHLIST: "/wishlist",
    CATEGORY: "/category",
    CONTACT: "/contact",
    DETAIL_ITEM: "/detail-item/:id",
    CHECKOUT: "/checkout",
    ACCOUNT: "/account",
    LOGIN: "/login",
    SIGNIN: "/signin",
    NOTFOUND: "/404-notfound",
}